### ISSUE TITLE
Pokemon Catch Flee

### ISSUE THREAD

**Issue by Asriandy** [NoxxDev/NecroBot#128]
Whats going on? Can't catch pokemon...

![ss](https://cloud.githubusercontent.com/assets/20786218/17732312/f6ccb740-6425-11e6-9260-39a114cd22b7.png)

**Comment by crisperfx** [comment]
This is a softban, you have to wait for 24h to play again (time is not precise). More to find: https://unbanster.com/remove-catch-flee-soft-ban-pokemon-go/

**Comment by Asriandy** [comment]
Ok, just another soft ban...
Does it matter if I continue bot to collect XP from looting pokestop?

**Comment by AmazingGamerBoy** [comment]
risky...

**Comment by crisperfx** [comment]
I would suggest not to use your account for about 24h, just make another account if you'r really bored ;)
And maybe (i hope for you) your account will not been perma banned after that. I also suggest to use my config which been used for 8 days without softban or perma ban due to the humanized edit: http://pastebin.com/qXrYAGRi And avoid running the bot more then 4h, take 1h rest ;)

**Comment by Asriandy** [comment]
Ok...
Should wait for tomorrow...
@crisperfx i hv another account... i will try ur config...
 Thank u all

**Comment by tansengcopao** [comment]
@Asriandy I noticed your bot recycled quite often. Can you show me your recycle config?
