### ISSUE TITLE
 Anyone Feel Free For Argue. How to safe from banned?

### ISSUE THREAD

**Issue by lucky4com** [NoxxDev/NecroBot#179]
How to bot without getting banned?
lat, long on bot i'm set on newyork
and my lat, long on asia

when i want to login into my mobile
what should i do? with out getting softban or etc

when i'm auto snipping with necrobot
the bot catch the pokemon with distances lat, long 

whether it will get banned too??

please help

**Comment by dickkyhenriette** [comment]
yes dont use it if you lucky maybe they mis you

**Comment by RavenHome1** [comment]
avoid sniping, it will flag your account for ban

 lat and long should be relatively close to where you first booted the game from mobile

do not disable humanized walking and throwing

do not leave the bot running more than 10 hours since a normal human won't play for that long (the ones without much dedication at least)

avoid settings that lead to suspicious acts, ex 0ms between player actions, running speed over 15km/h..etc

**Comment by smoothrunnings** [comment]
@RavenHome1 I have met a few people who have been playing Pokemon Go in my neck of the woods who haven't cheated at all. They are hitting level 30 now. This is a sign that people who are level 30 ~ 40 a week or two ago likely farmed their way. :)

**Comment by lucky4com** [comment]
Thanks You so much @RavenHome1

**Comment by RavenHome1** [comment]
@smoothrunnings yeah but getting to level 30  quickly will raise some flags. better safe than sorry i would say.
