### ISSUE TITLE
For those having problems with 9.3 Release just use 9.0

### ISSUE THREAD

**Issue by likeness123** [NoxxDev/NecroBot#297]
If you have problems with 9.3 just use the 9.0 verson. No more hassle for the API key and kill switch where Niantic easily detects.

**Comment by Ev0luti0n2016** [comment]
The way that I was able to fix this and get 0.9.3 working is to do the following:

1-Start 0.9.2
2-Accept update
3-DO NOT configure your account -->It will make an empty config
4-Edit the new auth.json and config.json with your info
5-Start the bot
6-Have fun and hope that your account does not get banned

**Comment by likeness123** [comment]
I am using 9.1 release I think it is better. I have not yet got any softbans.

**Comment by clash-votter** [comment]
v0.9.0 doesn't seem to be running into the softbans that its newer counterparts are facing (i.e. not seeing any objects on the map after some time: v0.9.1 and up). I would certainly recommend 0.9.0 for now.
This could be related to later versions' use of Rocket API? (See issue #293 ).

**Comment by RavenHome1** [comment]
is the api undetectable in 9.0?, i highly doubt so.

**Comment by clash-votter** [comment]
If everything seems to work, would you consider that 'undetectable?' Yes of course. It's not detected, no precautions are being taken via softban. Pretty pointless if you'd ask me that. Unless you bot for 24 hours straight. 8 hours even. Easy to conclude that's not a human playing the game.

So there Is a difference between 0.9.0 and later versions, since it is running smoothly. Might be a good idea if the devs make v0.9.0 a 'stable' build, and the later versions a 'dev' branch.

**Comment by RavenHome1** [comment]
i never had the softbans spam in the 9.3 build. what if ninatic can detect the bot with the correct api but are not taking any actions until they take players by surprise in wave ban.

**Comment by clash-votter** [comment]
The softban that occurs in v0.9.3 includes a point in time when the bot can't see any objects on the map. Back to v0.9.0 and none of the sort.

**Comment by evs38** [comment]
Every unofficial API are detectable now

**Comment by ausscheider** [comment]
i have problem with all version after 0.9.0 
only 0.9.0 works, the other .1 .2 .3 not works
