### ISSUE TITLE
Idea for Improvment: Do not walk always on top of Pokestops

### ISSUE THREAD

**Issue by CadroCZ** [NoxxDev/NecroBot#299]
Hi Guys,

I was thinking it would be good idea to implement collecting poke stops from short distance.

1) Easy to detect that every single poke stop was collected exactly at your location = poke stop location. You would never do that in real life

2) It is annoying with google walking implemented. In my case it uses always streets/paths even in parks and then it goes to poke stop, return to the street and continue. Visualized path then look like "TTT" for 3 stops on 1 street. Collecting from the street if in reach would be much better/faster/safer

WDYT?

M.

**Comment by ValorRed** [comment]
May I add one? Not sure if it is implementable, or will it be limited by Google Walk:
When Speed set is <8, can the walking path a little besides the road, if possible , only apply it to the bigger road. So that it looks like in the pedestrian walk way.

If 5 km/h, but walk in a middle of a main road, it's not real.
