### ISSUE TITLE
Has anyone ever realised

### ISSUE THREAD

**Issue by dbw-holic** [NoxxDev/NecroBot#301]
Anything that has been discussed here will be seen by staff from Niantic, And they can act ASAP most likely processing prevention before any new ideas are added to next Necrobot release? Isn't it just like we are telling them "Hey Look, Niantic! We have got some other cool ideas that you may consider and thus add to the banning criteria!"
So when a new function is eventually added to next release and end user just run it, at the same time, on Niantic's servers they will be like "awesome, there we go, expected new tricks, BAN!"

**Comment by nutsky** [comment]
the source code are open anyway, they can check what has been committed for every release

**Comment by ValorRed** [comment]
The game is lame. Th fun is in the progress of attacking with bot and defending with ban. Lol

**Comment by kalamera** [comment]
They can even change the bot to provide special marks on users using it.
No doupt they do that ;)

**Comment by ShadXo** [comment]
But we can see the commits :)

**Comment by Iccyman0102** [comment]
Niantic can only commit so much manpower to bot prevention. Pogo is tanking in overall rankings, it is popular in metro areas and mostly unplayable in rural areas, they need to devote some serious developer time into fixing the issues to avoid the decline  in userbase which is already happening. In this respect I think the bots will win out over the long haul because Pogo's investors will want to see some progress in the game and anti-botting is not visible progress, its stop-gap...
