### ISSUE TITLE
Feature request - 

### ISSUE THREAD

**Issue by joehsmash** [NoxxDev/NecroBot#303]
Add a variable to the % of missed throws, 

when enabled i have mine set to 18% (default is 25) but would be nice if there was a variable in there like the walking does. 

one time its 18% another time is 22% so on and so forth

would just add another level of humanization to it

**Comment by petpetpetvm** [comment]
lol, the game can't see your % but they can see your speed
the % just make the bot randomly misses the throw at how many %, not like speed lol

**Comment by joehsmash** [comment]
honestly if i knew enough about the code to write one of these i would... but seeing as i don't how would i know that it cant see that?

was just a suggestion no need to treat it like a joke...

**Comment by petpetpetvm** [comment]
of course the game can't see the 18% (of 25%) because let say
1st throw have 18% miss and its not
2nd throw have 18% miss and its not
3rd throw have 18% miss and its not
the game will see that it's 100% with no miss

but yeah, it will be better if the % will be increase if it's not missed (and reset back to 18% when it's missed)
i'm not sure it's that what you mean but it will be better

and i don't know and don't care about your coding thing :)

**Comment by petpetpetvm** [comment]
or* 25%
