### ISSUE TITLE
Start with bot, then open official app in mobile

### ISSUE THREAD

**Issue by zzzz9999** [NoxxDev/NecroBot#313]
I started playing with bot, all the way till Level 18.
Then opened game in official app.
Then appeared initial welcome wizard, the professor, the first 3 tutorial pokemon, pokestops tutorial, etc. I made all this steps as a L18 trainer.

Cant this be suspicious?

(An advise, before using bot maybe should be better open game in mobile and do that wizard/tutorial first)

**Comment by dbw-holic** [comment]
I think most of the players will just walk through the initial setting first? I mean that's obviously not possible if you were a legit player.

**Comment by likeness123** [comment]
One of the best advice is use a bot but use your own lat and long in your own city or country because that way it will be less suspicious.

**Comment by Iccyman0102** [comment]
I have gotten into the habit of first loading my new accounts into my phone app, setting Nickname, catching starter, etc... Then I leave the account logged-off for a couple of days so I can then use the bot in a specific location without it looking too suspicious (warp gps). I agree that going through the starter pokemon and setting nickname anytime after level 1 is incredibly suspicious since it doesn't happen in the app.
