### ISSUE TITLE
Killswitch Pokestops/Caught Pokemon/FleePokemon Resetting

### ISSUE THREAD

**Issue by Koshyy** [NoxxDev/NecroBot#325]
How is the Killswitch supposed to work? Is it supposed to track for the entire session the bot is open? Is it supposed to reset once per hour? If it is supposed to reset once an hour, why doesn't it automatically start again when a limit is reached and an hour has passed? Not really a bot if you have to press a button to continue -.-

Some information on HOW it's supposed to work would be appreciated.

**Comment by k0lev** [comment]
I think it currently works on hourly basis, this is why i made a batch file that opens/closes the bot in case  it has been killed by some limit it reached... this is the code, but needs adjusting for your bot locatoin, just edit it:
http://pastebin.com/xebsvvGk

It automates it for 16 hours and 8 hours sleep (increase limits to 16 hours working per day)

**Comment by YouGamePlayHD** [comment]
Ok, your skript lets the bot reopen? Great work, man!
+1

**Comment by Koshyy** [comment]
awesome dude. can someone explain why this didn't come stock with killswitch.. it isn't a bot if it doesn't automatically restart, kind of defeats the purpose -.-

**Comment by Koshyy** [comment]
@k0lev also I'm wondering, if killswitch stops the operation... will it wait for the remaining of the hour before it restarts?

**Comment by k0lev** [comment]
@Koshyy My current code does the following:
Starts necrobot and leaves it working for a random number between 3600 and 3690 sec (1 hour to 1h1min30sec), then it closes necrobot.
After that, it starts it again and leaves it to work again for the same time (randomly between that number so no pattern is left).
This will happen 16 times per day and then pause the bot for 8 hours before starting over from 1 in the next day. Everything is randomly set, so they can't find pattern in the closing/opening of the bot

The idea is to limit your killsiwtch to 16 h work (60/h not 40 as is the default). It might not need the close (not reached the limit), but it will anyway. This way you are sure you don't need to pay attention to the bot and it will never get banned, since it works the limit.

It's your job to push it to the limit, so it actually uses it in that hour... I didn't explain well enough, but..

**Comment by Koshyy** [comment]
@k0lev yeah, looking through the code now, makes sense. Yeah, next step will be seeing what limit I can push it to, just want to make sure it can run 24 hours on base settings first :)

Thanks for the more detailed description :P I just woke up so wasn't really paying attention to the code :$ my apologise
