### ISSUE TITLE
0.9.4 problem!

### ISSUE THREAD

**Issue by tonigino2** [NoxxDev/NecroBot#355]
Hi!
Tomorrow i updated my necrobot client, i setted it up and then it says this error
![immagine](https://cloud.githubusercontent.com/assets/21101446/17836555/d0eed2a0-6796-11e6-9a25-02da93558626.png)
I also tried to download it from the github and set it up but this always happens.

**Comment by maboigorilla** [comment]
Download it and delete Necrobot.exe and run the necrobot . It worked for me

**Comment by ausscheider** [comment]
Look here -->> https://github.com/NoxxDev/NecroBot/issues/358

**Comment by tonigino2** [comment]
@maboigorilla  @ausscheider  I did it but i have the same problem

**Comment by 4ntani** [comment]
Me too

**Comment by ausscheider** [comment]
you have exactly do --> https://github.com/NoxxDev/NecroBot/issues/358 <<-- this one and have the same problem?

**Comment by tonigino2** [comment]
@ausscheider  Yes

**Comment by ausscheider** [comment]
@tonigino2 
after run necrobot.exe come the question of setup, here you say no?

**Comment by 4ntani** [comment]
Download the latest release --> Ok
unpack release.zip --> Ok
start NecroBot.exe --> for do it i must change "Translation folder" but anyway it not work!

![image](https://cloud.githubusercontent.com/assets/21153408/17836721/67200dac-679c-11e6-98df-b426dc266c56.png)

I remove Necrobot.exe.config and still don't work

I paste my old auth.json and it works!

By the Question: Would you like begin the setup? -->> No
Go to the Folder "Config"
open the file auth with notepad and make your personal settings
save the file
open the file config with notepad and make your personal settings
save the file
start NecroBot.exe
Have Fun
Remember 1 IP = 1 Bot


At the moment everything works!!! Thanks a lot for the help... The problem was in auth config...

**Comment by alexbaas** [comment]
https://github.com/NoxxDev/NecroBot/issues/326 Look here, this worked for me

**Comment by NoxxDev** [comment]
v0.9.7 release
