### ISSUE TITLE
(Request)(Issue)Killswitch not maximizing XP

### ISSUE THREAD

**Issue by hardknoxni69a** [NoxxDev/NecroBot#407]
@NoxxDev 
Hello I would like to note that the bot should probably have a switch for the killswitch.
If we meet our goal for catches it should stop catching and proceed to finish the pokestop goal.
If we meet our goal for pokestops it should stop spinning and proceed to finish the catch goal.
With this implemented we won't be losing out on the extra potential XP for our hour.
A more complete way would be in issue/request #340 
And of course thank you so much for all your hard work!!

**Comment by BoydTM** [comment]
please take into consideration that it will only create additional pattern for niantic to identify necrobot. static amount of actions may be easy to detect for someone who knows how to use the database (repeating the same amount of pokemon catches, pokestops or even unban attemps (always 45) is suspicious as hell ... ). It would be a lot better to use ranges instead of static numbers (or maybe something similar to a mechanism which constantly changing the walking speed (excelent idea BTW)

**Comment by hardknoxni69a** [comment]
even better implement a variant into the new killswitch add the maximizing of it but have a variant so one time it will catch 80 then 85 then 75 very good idea depending on how the user has it set

**Comment by clash-votter** [comment]
Please dont bring up issue #340 again. Jesus Christ that punctuation is f*kn stupid. How do you expect hard work to be done for you when you Cant Even Communicate Properly. Just f*kn stupid.

On a different note, I'm here to address the problem.
It's pretty popular that the limit is around 1000pokemon/24 hours and 2000pokestop/24 hours.

The problem with this limit is it's based on 24 hours **clock** time, not hours run time of the bot.

So let's say I catch 1000 pokemon in 12 hours, then other 12 hours Im logged out. That's still valid.
Next day I can do the same thing.

So it's better to calculate the rates of catch and spin using calendar date & system time. Only one step now to implement this properly:

1. Get a counter for amount of pokestops/pokemon farmed (even when bot is off), and their catch/spin times related to the system time.

And the logic:
SO now we let the bot do its thing. Eventually it will catch the 1000th pokemon. Let's say it caught the 1000th pokemon on 7pm.

At this point, this is when the bot should check **if 24 hours has passed since pokemon number 1 was caught**. If it hasn't, then the bot stops catching pokemon.
The bot will stay not catching any pokemon until the next day is reached - 24 hours after the time from pokemon number 1, then it will catch pokemon again.

Logic checks:
A) So let's say the time from pokemon 1 to pokemon 1000 is exactly 24 hours. This means we Just hit the limit and the bot can keep catching pokemon.

B) Let's say the time from pokemon 1 to pokemon 1000 is just below 24 hours. This means it has to wait for exactly 24 hours to pass before allowing to catch any pokemon again.

C) Let's say the time from pokemon 1 to pokemon 999 is 24 hours. This means we Just didn't hit the limit, and the bot can keep catching pokemon.
Now at this point the next pokemon is pokemon 1000. We should now **reset** the counter so this pokemon 1000 is pokemon 1 of the next day.

Same case for the checks A) and B), after 24 hours the next pokemon is pokemon number 1.

And so this cycle will continue. This works because as long as the bot doesn't get 1000 pokemon in 24 hours, the bot can keep going. Once it catches pokemon 1 to pokemon 1000 in 24 hours or less, it will have to wait until 24 hours has passed from pokemon 1 before starting again.

Same logic for pokestops, only difference is from pokestop 1 to pokestop 2000.

Now I do have logic right here, but it is not in the right language. I'm sure the devs would kindly translate this logic to code.

PS I apologise in behalf of the community for that Terribly Punctuated Issue.
@NoxxDev

**Comment by clash-votter** [comment]
Aight for even more help, this is my 'pseudo-code' for this logic, lol if you can even call it that.

```
/* Start */
counterpokemoncaught == 0

IF (a pokemon is caught && counterpokemoncaught == 0) {
counterpokemoncaught++
Record Time HERE
}
IF (a pokemon is caught && counterpokemoncaught > 0) {
counterpokemoncaught++
}
/* Now: */
IF(counterpokemoncaught == 1000 && Current time - Record time HERE <= 24 hours) {
Stop Catching Pokemon
}
ELSE
Keep catching pokemon

/* Resetting the counter every 24 hours */
IF(Current time - Record time HERE == 24 hours){
counterpokemoncaught == 0
}

/* Then back to the start */
```

**Comment by clash-votter** [comment]
UPDATE: This problem seems to be already addressed (see #337 ).

**Comment by hardknoxni69a** [comment]
337 is a little different we need it to maximize the xp for both not just shut off once it hits a single goal. And it cant be set as just a certain run time say we caught all 1000 in 12 hours it may allow us to recatch in 12 more hours but today more pokemon are spawning and we caught the 1000 in only 10 hours this would trigger the ban because within the 24 hour window we went over the limit we need it to actively monitor the log so it knows once we reach say 5:43:12 it will be allowed the catch 1 pokemon because 24 hours ago at 5:43:11 it caught the 1st pokemon then the second pokemon was caught at 5:44:05 we need the bot to not allow second pokemom till 5:44:06 because catching speed varies depending on area this is why i believe we need the revolving clock as discussed in #340

**Comment by hardknoxni69a** [comment]
People like votter are the reason people dont communicate its a capitol letter #340 is explained pretty well we need to support eachother not get all sad and upset over a capitol letter

**Comment by lkhgamer** [comment]
![necro](https://cloud.githubusercontent.com/assets/20950902/17887252/cdf19802-694f-11e6-856e-ea00c3ea196c.jpg)
16 minutes only catch 3 pokemon ^_^ slower than last version

**Comment by hardknoxni69a** [comment]
You probably have your speed down and google walk on which makes u take a longer route not to mention your location is horrible almost a km between stops

**Comment by lkhgamer** [comment]
"WalkingSpeedInKilometerPerHour": 7.16, <<<< is it has to set 10 ???

  "GoogleWalkConfig": {
    "UseGoogleWalk": true, <<<< is it has to set off ???
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "",
    "Cache": true

**Comment by hardknoxni69a** [comment]
Your speed is personal preference i have mine set to 22.5 so it hatches eggs still and 2.5 variant. they know everyone drives or bikes its like 18mph i think and the google walk is main problem as it stays on the main path its no longer walking directly through the pentagon lol so yes set to false if u want to stop that

**Comment by hardknoxni69a** [comment]
@NoxxDev fixed this issue by now maximizing ip and even maximizing walking your the man thanks
