### ISSUE TITLE
Perma ban using 0.9.0

### ISSUE THREAD

**Issue by tuxfrw** [NoxxDev/NecroBot#438]
Perma ban using 0.9.0 with default configuration.  :(

**Comment by Skolzack** [comment]
No one is safe, every configs aren't safe. For now Niantic is winning.

**Comment by xhaoran06** [comment]
^Yep, and just awhile ago my account got banned. LMAO

**Comment by clash-votter** [comment]
Can confirm permaban wave has hit. My account also banned. v0.9.0 was released 7 days ago. Weekly permabans confirmed?

**Comment by clash-votter** [comment]
Bots really need to simulate the game client. #336 really needs to be addressed, otherwise all accounts are marked for a permaban.

**Comment by tuxfrw** [comment]
kkkkk trying again. But I'll wait for version 0.9.5  :)

**Comment by clash-votter** [comment]
Idgaf about bans anymore.
As eloquently put in #301 
"The game is lame. The fun is in the progress of attacking with bot and defending with ban. Lol"

**Comment by xhaoran06** [comment]
I really think that connecting and disconnecting simultaneously on maps.googleapis.com at every pokestops somehow get our accounts pin pointed for using bot or something. Since using devices don't do this.

8/23/2016 10:57:45 AM - Tunnel - NecroBot.exe: Connect to maps.googleapis.com:443 success
8/23/2016 10:57:45 AM - Tunnel - NecroBot.exe: Disconnect maps.googleapis.com:443, send 438 bytes, recv 5.33k, time 343ms.
