### ISSUE TITLE
[Feature] suggestion. 

### ISSUE THREAD

**Issue by smoothrunnings** [NoxxDev/NecroBot#452]
1. when you stop and start Necrobot the bot needs to use the last coordinates as the starting point.
2. add some kind of scheduling feature to start and stop the bot at certain times. People don't farm 24/7, they maybe spend 4 hours a day farming. Once school is in again farmers will be easy to identify. 

thanks!

**Comment by kalamera** [comment]
1. it does when the travel distance is not realistic.
2. you can use the Windows Task Scheduler, like start at specific time, run for specific time and so on...

**Comment by smoothrunnings** [comment]
@kalamera 

1. it needs to be done by default or by using a option in the config. Because if you start and stop the app while you are not around you won't be able to copy and paste the coordinates in.

**Comment by kalamera** [comment]
well i would rather prefer to get the first coordinates from GPX file as start position instead of the default coordinates in the config file.
it is little bit annoying when you want to switch GPX file and you have to edit 3 lines in the config file everytime.

also would be nice to input the gpx file as an parameter at cmd line instead of editing the config file everytime.

**Comment by tiggerite** [comment]
@smoothrunnings in the latest source, it does exactly that, reads from LastPos.ini as long as you have StartFromLastPosition true (it is by default).
@kalamera as for GPX, again in the latest source it will jump to the closest point in your GPX from either the position in LastPos.ini or your default lat/long, as long as these are not more than 5km from that point. Possibly even that 5km check could be removed as it hasn't sent those coords to the server yet.
