### ISSUE TITLE
About official data collected

### ISSUE THREAD

**Issue by mkcs121** [NoxxDev/NecroBot#472]
Does Niantic collect the data of gyroscope and signal strength in PoGo App? Can Necro mimic if such data is collected for identifying botting?

**Comment by kalamera** [comment]
And what about compass?
I am sure even the old version of PoGo App did use the compass data, but the bot did not I suppose.
Another red flag for botters :)

**Comment by kalamera** [comment]
Not sure about the baroscope...

**Comment by MV1977** [comment]
But what does Pokemon Go return if these are not available (e.g. on the phone I use, the "battery saving" does not work, nor does AR, since PoGo cannot determine this on my phone)?

**Comment by smoothrunnings** [comment]
@mkcs121 Niantic logs all data. As I have said before they have been in "dealing with cheater" before Pokemon Go was even the shining light in their eyes. lol   Their previous game which bombed and was the earlier version of Pokemon Go had a lot of cheaters which is why they have a head start now when it comes to detecting cheaters.

**Comment by Kermel** [comment]
Gyroscope data, location data, even the magnetometer data are alrady part of the requests sent via pogo API.
(all randomized values (except for the location) of course)
The question is if this is enough :)
