### ISSUE TITLE
[Request] Make the bot check for PokeStops

### ISSUE THREAD

**Issue by YouGamePlayHD** [NoxxDev/NecroBot#529]
This is a servere problem I have. The bot selects one PokeStop and walks to it - good. But the stops it passes are not collected. This is suspicious (which normal player would collect no stops on its route?!). I'd recommend adding a feature that the bot checks for PokeStops around it all the time when it's walking. That would make it really hard for Niantic detecting your bot and would certainly improve it.

**Comment by timonibus** [comment]
I think this has to do with how the bot determines the nearest Pokestop. It seems to choose the nearest one according to the linear distance. This does not take into account that the actual way which is walked can be much longer if you use GoogleWalk. So I guess the problem is not that it does not collect Pokestops on to go but actually that it does not choose the closest one in terms of Google walking.

**Comment by kalamera** [comment]
Use GPX pathing, then it should take all the pokestops along the way it goes.

**Comment by YouGamePlayHD** [comment]
How do you use that?

**Comment by ValorRed** [comment]
With GPX pathing, the play walk wildly when using HumanWalk, at least with my test in 0.9.5
