### ISSUE TITLE
0.9.6 StartFromLastPosition does not work with GPX pathing

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#558]
As title says. I have confirmed this multiple times.

**Comment by vfuyong** [comment]
Hmm it may be related how the bot closes. If it closes unexpectedly, the last position may not be saved properly.

**Comment by mo0ojava** [comment]
Just noticed the following:
+ If you set DefaultLatitute & DefaultLongitude to somewhere along your GPX-track, the bot looks up the (first) relevant location in the file and continues from there. Works.
+ When you reach the end of the GPX-track the bot starts a beeline for the initial DefaultLatitude & DefaultLongitude instead of restarting the GPX-track. Broken.

It may be that StartFromLastPosition isn't really the culprit. It's could be that the bot prioritize to (erroneously) return to the config.json-default, just as when finishing a GPX-track. Might look into that a bit later.
