### ISSUE TITLE
something worry with my necroBot

### ISSUE THREAD

**Issue by ZBrettonYe** [NoxxDev/NecroBot#616]
![10](https://cloud.githubusercontent.com/assets/18015854/18024493/365cbec6-6c3e-11e6-8075-be3835774b7e.jpg)

windows：7
i ready installed the net and c++

first time run the bot , just a black screen, nothing shows out. can anyone help me?

**Comment by CreativiTimothy** [comment]
probably slow Internet connection

**Comment by BlueVeeVee** [comment]
It is internet connection problem.  
it will show you "Exception caught, writing LogBuffer" error later.

Solution:
if you are in some countries that block google servers,you need to use Google host or VPN for running necrobot 9.1 and above. This is due to google route feature that has been added in necrobot 9.1 and above.
