### ISSUE TITLE
Transfer Only Weak Pokemon Not Working

### ISSUE THREAD

**Issue by mucro9** [NoxxDev/NecroBot#844]
İ before update used pretty but after update nothing to transfer is same config

"TransferWeakPokemon": true,
    "TransferDuplicatePokemon": false,
    "TransferDuplicatePokemonOnCapture": false,

**Comment by seouljah760** [comment]
# **Utilize this format when having config issues:**

### Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check. 

## YES or NO

### Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead. 

## YES or NO

### Have you searched the wiki? Is it unclear? Does it not have what you're looking for?

## YES or NO. Explain

## Expected Behavior

Pokemon are transferring based on config

## Actual Behavior

Pokemon are NOT transferring based on config

## Your config.json

www.pastebin.com/yourconfig.json

##  Steps to Reproduce

insert pertinent information here

## Other Information

Version: 0.9.7
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): transfer

insert pics here

-----------------------------------------------------------------------------------------------------------------

**Comment by CreativiTimothy** [comment]
#702

**Comment by seouljah760** [comment]
Thanks @CreativiTimothy

**Comment by mucro9** [comment]
So ?

**Comment by seouljah760** [comment]
Close. This. Issue. Please.
