### ISSUE TITLE
Transfer between catch attemps

### ISSUE THREAD

**Issue by ValorRed** [NoxxDev/NecroBot#855]
This really need to be fixed. Unreal behaviour:
![image](https://cloud.githubusercontent.com/assets/20829876/18231824/dbdcda04-7290-11e6-8c07-0a67b3526aef.png)

Transfer other pokemon shall only happen after CatchSuccess or CatchFlee. And it would be nice if it is always provide a 15+ sec delay (With some random) after CatchSuccess, that's how much time the real Pokemon go show the caught video and human press ok etc.

**Comment by GitUpA** [comment]
I have noticed this also.

**Comment by seouljah760** [comment]
# **Utilize this format when having config issues:**

### Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check. 

## YES or NO

### Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead. 

## YES or NO

### Have you searched the wiki? Is it unclear? Does it not have what you're looking for?

## YES or NO. Explain

## Expected Behavior

Pokemon are transferring based on config

## Actual Behavior

Pokemon are NOT transferring based on config

## Your config.json

www.pastebin.com/yourconfig.json

##  Steps to Reproduce

insert pertinent information here

## Other Information

Version: 0.9.7
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): transfer

insert pics here

-----------------------------------------------------------------------------------------------------------------

I can answer your question when you post in the right format and submit your config. I already have the answer.

**Comment by mo0ojava** [comment]
This has been fixed in the current dev-builds.

**Comment by NoxxDev** [comment]
Fix in 17d3726b4c13a59d6dfd332229c3230027c989ff
