### ISSUE TITLE
[Request] start coordinate suggestion

### ISSUE THREAD

**Issue by smoothrunnings** [NoxxDev/NecroBot#92]
If the last coordinates are close the default ones, it would suggest the player was farm in the same area recently. It would be nice to see the bot change the coordinates by a degree or two or choose something that is a little more random in the same area when the start. 

Again thinking more human like, what's the possibility you are going to start in the exact same location each time?

**Comment by JoNMii** [comment]
+1 Or this, or add some noise to default cords

**Comment by SniperVegeta** [comment]
also when closing to program, maybe to add a time of closing,
when running the program again, for example that u closed it ecedently, you will "teleport" to the start cordinate

so the program could know, you start it to fast, and open te last cords, instead of teleport you to the beginning.

and maybe to add a question. 
wanna start off at your old location? Y/N
if yes = resume
if no = your start location ( maybe whit that degree noise ratio )

**Comment by NoxxDev** [comment]
v0.9.5 or upper, bot change random default start
